// signupStyles.ts
import { SxProps, Theme } from '@mui/system';

export const signupStyles: { [key: string]: SxProps<Theme> } = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '50vh',
    backgroundColor: '#ffffff',
    width: '100%',
    maxWidth: '31rem',
    margin: '0 auto',
    position: 'relative',
    boxShadow: '0rem 0.2em 0.8em 0px #00000033',
    borderRadius: '0.625rem',
    border: '0.125rem solid transparent',
    marginTop: '7.5em',
    '@media (max-width: 440px)': {
      boxShadow: '0rem 0px 0px 0px #00000033',
      border: 'none',
      marginTop: '3.75em',
    },
  },
  logoContainer: {
    paddingLeft: '2.5em',
    paddingRight: '0.5em',
  },
  title: {
    mb: 2,
    fontWeight: 'bold',
    fontSize: '28px',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    padding: '1.5rem 1rem 2.5rem',
    fontFamily: 'Nunito',
  },
  googleButton: {
    mb: 2,
    bgcolor: '#FFFFFF',
    color: '#000000',
    padding: '0.875rem 7.5625rem',
    whiteSpace: 'nowrap',
    border: '0.125rem solid transparent',
    '&:hover': {
      borderColor: '#Grey/Light',
      backgroundColor: 'white',
    },
    textTransform: 'none',
    width: '100%',
    maxWidth: '22.5rem',
    fontWeight: 'medium',
    fontSize: '0.875rem',
  },
  orDivider: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    maxWidth: '22.5rem',
    mt: '24px',
    mb: '24px',
  },
  orText: {
    px: 2,
    fontWeight: 'regular',
    fontSize: '14px',
    fontFamily: 'Nunito',
  },
  form: {
    width: '100%',
    maxWidth: '360px',
    padding: '0 0px 24px',
    fontFamily: 'Nunito',
  },
  inputLabel: {
    fontFamily: 'Nunito',
    fontSize: '16px',
  },
  submitButton: {
    mt: 2,
    backgroundColor: '#FFFFFF',
    color: 'rgba(244, 87, 69, 1)',
    '&:hover': {
      backgroundColor: 'rgba(244, 87, 69, 1)',
      borderColor: 'rgba(244, 87, 69, 1)',
      color: 'rgba(255, 255, 255, 1)'
    },
    fontWeight: 'bold',
    margin: '24px 0px 0 0px',
    textTransform: 'none',
    minHeight: '3rem',
    fontSize: '16px',
    fontFamily: 'Nunito',
  },
  loginText: {
    mt: 2,
    margin: '40px 0px 24px',
    fontFamily: 'Nunito',
    fontSize: '16px',
  },
  loginLink: {
    color: '#F45745',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontFamily: 'Nunito',
    textDecoration: 'none',
  },
};
