from enum import Enum, auto


class BaseEnum(Enum):
    SUCCESS = 'SUCCESS'
    FAILURE = 'FAILURE'


class StripePaymentStatusEnum(Enum):
    COMPLETE = 'COMPLETE'
    ONGOING = 'ONGOING'
    PENDING = 'PENDING'
    FAILED = 'FAILED'

class SubscriptionStatus(Enum):
    SUCCESS = "SUCCESS"
    INCOMPLETE = "INCOMPLETE"
    PAST_DUE = "PAST_DUE"
    CANCELED = "CANCELED"
    UNKNOWN = "UNKNOWN"
    NEED_UPGRADE_PLAN = 'NEED_UPGRADE_PLAN'
    
class SettingStatus(Enum):
    INCORRECT_MAIL = 'INCORRECT_MAIL'
    SUCCESS = "SUCCESS"
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
    RESEND_TOO_SOON = "RESEND_TOO_SOON"
    EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED"
    FAILED = 'FAILED'
    ALREADY_INVITED = 'ALREADY_INVITED'
    INVITATION_LIMIT_REACHED = 'INVITATION_LIMIT_REACHED'
    INVITATION_LIMIT_NOT_REACHED = 'INVITATION_LIMIT_NOT_REACHED'
    INVALID_ACCESS_LEVEL = 'INVALID_ACCESS_LEVEL'


class VerificationEmail(Enum):
    EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED'
    EMAIL_VERIFIED = 'EMAIL_VERIFIED'
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED'
    CONFIRMATION_EMAIL_SENT = 'CONFIRMATION_EMAIL_SENT'
    RESEND_TOO_SOON = 'RESEND_TOO_SOON'


class UserAuthorizationStatus(Enum):
    SUCCESS = 'SUCCESS'
    NEED_CHOOSE_PLAN = 'NEED_CHOOSE_PLAN'
    NEED_CONFIRM_EMAIL = 'NEED_CONFIRM_EMAIL'
    FILL_COMPANY_DETAILS = 'FILL_COMPANY_DETAILS'
    NEED_BOOK_CALL = 'NEED_BOOK_CALL'
    PAYMENT_NEEDED = 'PAYMENT_NEEDED'
    PIXEL_INSTALLATION_NEEDED = 'PIXEL_INSTALLATION_NEEDED'


class MiddleWareEnum(Enum):
    NEED_EMAIL_CONFIRMATION = 'NEED_EMAIL_CONFIRMATION'


class SignUpStatus(Enum):
    NEED_CHOOSE_PLAN = 'NEED_CHOOSE_PLAN'
    NOT_VALID_EMAIL = 'NOT_VALID_EMAIL'
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
    PASSWORD_NOT_VALID = 'PASSWORD_NOT_VALID'
    NEED_CONFIRM_EMAIL = 'NEED_CONFIRM_EMAIL'
    FILL_COMPANY_DETAILS = 'FILL_COMPANY_DETAILS'
    TEAM_INVITATION_INVALID = 'TEAM_INVITATION_INVALID'
    INCORRECT_STATUS = 'INCORRECT_STATUS'
    SUCCESS = 'SUCCESS'
    
class TeamsInvitationStatus(Enum):
    PENDING = 'pending'
    
class TeamAccessLevel(Enum):
    ADMIN = 'admin'
    STANDARD = 'standard'
    READ_ONLY = 'read_only'

class LoginStatus(Enum):
    INCORRECT_PASSWORD_OR_EMAIL = 'INCORRECT_PASSWORD_OR_EMAIL'
    SUCCESS = 'SUCCESS'
    NEED_CHOOSE_PLAN = 'NEED_CHOOSE_PLAN'
    NEED_CONFIRM_EMAIL = 'NEED_CONFIRM_EMAIL'
    FILL_COMPANY_DETAILS = 'FILL_COMPANY_DETAILS'
    NOT_VALID_EMAIL = 'NOT_VALID_EMAIL'
    NEED_BOOK_CALL = 'NEED_BOOK_CALL'
    PAYMENT_NEEDED = 'PAYMENT_NEEDED'
    PIXEL_INSTALLATION_NEEDED = 'PIXEL_INSTALLATION_NEEDED'


class PixelStatus(Enum):
    PIXEL_CODE_INSTALLED = 'PIXEL_CODE_INSTALLED'
    PIXEL_CODE_PARSE_FAILED = 'PIXEL_CODE_PARSE_FAILED'


class UpdatePasswordStatus(Enum):
    PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH"
    PASSWORD_UPDATED_SUCCESSFULLY = 'PASSWORD_UPDATED_SUCCESSFULLY'


class SendgridTemplate(Enum):
    EMAIL_VERIFICATION_TEMPLATE = 'email_verification_template'
    FORGOT_PASSWORD_TEMPLATE = 'forgot_password_template'
    SEND_PIXEL_CODE_TEMPLATE = 'send_pixel_code_template'
    CHANGE_EMAIL_TEMPLATE = 'change_email_template'
    TEAM_MEMBERS_TEMPLATE = 'team_members_template'


class ResetPasswordEnum(Enum):
    SUCCESS = 'SUCCESS'
    NOT_VALID_EMAIL = 'NOT_VALID_EMAIL'
    RESEND_TOO_SOON = 'RESEND_TOO_SOON'


class CompanyInfoEnum(Enum):
    SUCCESS = 'SUCCESS'
    NEED_EMAIL_VERIFIED = 'NEED_EMAIL_VERIFIED'
    NEED_CHOOSE_PLAN = 'NEED_CHOOSE_PLAN'
    DASHBOARD_ALLOWED = 'DASHBOARD_ALLOWED'


class AudienceInfoEnum(Enum):
    SUCCESS = "SUCCESS"
    NOT_FOUND = "NOT_FOUND"
    NOT_VALID_NAME = 'NOT_VALID_NAME'


class VerifyToken(Enum):
    SUCCESS = 'SUCCESS'
    EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED'
    INCORRECT_TOKEN = 'INCORRECT_TOKEN'
