US_STATE_ABBR = {
    "alabama": "AL",
    "alaska": "AK",
    "arizona": "AZ",
    "arkansas": "AR",
    "california": "CA",
    "colorado": "CO",
    "connecticut": "CT",
    "delaware": "DE",
    "florida": "FL",
    "georgia": "GA",
    "hawaii": "HI",
    "idaho": "ID",
    "illinois": "IL",
    "indiana": "IN",
    "iowa": "IA",
    "kansas": "KS",
    "kentucky": "KY",
    "louisiana": "LA",
    "maine": "ME",
    "maryland": "MD",
    "massachusetts": "MA",
    "michigan": "MI",
    "minnesota": "MN",
    "mississippi": "MS",
    "missouri": "MO",
    "montana": "MT",
    "nebraska": "NE",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    "ohio": "OH",
    "oklahoma": "OK",
    "oregon": "OR",
    "pennsylvania": "PA",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    "tennessee": "TN",
    "texas": "TX",
    "utah": "UT",
    "vermont": "VT",
    "virginia": "VA",
    "washington": "WA",
    "west virginia": "WV",
    "wisconsin": "WI",
    "wyoming": "WY",
    # For territories and aliases
    "dc": "DC",
    "district of columbia": "DC",
    "puerto rico": "PR",
}

# Some major cities -> state abbreviation
CITY_TO_STATE = {
    "dallas": "TX",
    "fort worth": "TX",
    "houston": "TX",
    "austin": "TX",
    "sacramento": "CA",
    "san francisco": "CA",
    "los angeles": "CA",
    "boston": "MA",
    "chicago": "IL",
    "philadelphia": "PA",
    "new york": "NY",
    "brooklyn": "NY",
    "atlanta": "GA",
    "miami": "FL",
    "orlando": "FL",
    "tampa": "FL",
    "minneapolis": "MN",
    "st. paul": "MN",
    "phoenix": "AZ",
    "denver": "CO",
    "salt lake city": "UT",
    "seattle": "WA",
    "las vegas": "NV",
    "new orleans": "LA",
    "nashville": "TN",
    "baltimore": "MD",
    "detroit": "MI",
    "pittsburgh": "PA",
    "st. louis": "MO",
    "arlington": "VA",
    "fairfax": "VA",
    "fredericksburg": "VA",
    "hartford": "CT",
    "mclean": "VA",
    "waco": "TX",
    "jackson": "MS",
    "tacoma": "WA",
    "eagan": "MN",
    "sioux falls": "SD",
    "smyra": "TN",
    "franklin": "TN",
    "flowood": "MS",
    "boulder": "CO",
    "lenexa": "KS",
    "cedar rapids": "IA",
    "anderson": "IN",
    "oklahoma city": "OK",
    "madison": "WI",
    "ames": "IA",
    "plummer": "ID",
    "richardson": "TX",
    "hendersonville": "TN",
    "newton": "MA",
    "wilmington": "NC",
    "spokane": "WA",
    "brentwood": "TN",
    "charlotte": "NC",
    "greensboro": "NC",
    "concord": "NH",
    "rochester": "MN",
    "peoria": "AZ",
    "vienna": "VA",
    "mesa": "AZ",
    "greenville": "TX",
    "hallandale": "FL",
    "maple grove": "MN",
    "carmichael": "CA",
    "eden prairie": "MN",
    "bloomington": "MN",
    "utica": "NY",
    "elizabeth city": "NC",
    "natchitoches": "LA",
    "warminster": "PA",
    "kalamazoo": "MI",
    "springfield": "MO",
}
