import React, { useRef, useState } from "react";
import { Box, Typography, Paper } from "@mui/material";
import CustomButton from "@/components/ui/CustomButton";

const PrivacyPolicy: React.FC<{
	onAccept: () => void;
}> = ({ onAccept }) => {
	const [scrolledToEnd, setScrolledToEnd] = useState(false);
	const contentRef = useRef<HTMLDivElement>(null);
	const [hovered, setHovered] = useState(false);

	const handleScroll = () => {
		const el = contentRef.current;
		if (el && el.scrollTop + el.clientHeight >= el.scrollHeight - 5) {
			setScrolledToEnd(true);
		}
	};

	return (
		<Box
			display="flex"
			flexDirection="column"
			justifyContent="center"
			width="800px"
			alignItems="center"
			margin="auto"
			border="1px solid #E4E4E4"
			boxShadow="1"
			padding={4}
			gap={3}
			borderRadius="6px"
		>
			<Box display="flex" flexDirection="column" gap={1}>
				<Typography className="heading-text" textAlign="center">
					Review Terms and Privacy Policy
				</Typography>
				<Typography className="tab-heading" textAlign="center">
					You must read through to continue
				</Typography>
			</Box>

			<Box>
				<Paper
					variant="outlined"
					sx={{
						p: 3,
						maxHeight: 400,
						maxWidth: 736,
						overflowY: "auto",
						borderRadius: "6px",
						"& p, & li, & ul": {
							fontFamily: "var(--font-nunito)",
							color: "#707071",
							fontSize: "14px",
						},
						"& li": {
							marginBottom: "0.5em",
							color: "#707071",
						},
						"& h1, h2, h3, h4, ol > li": {
							color: "#202124",
						},
					}}
					onScroll={handleScroll}
					ref={contentRef}
				>
					<h1>
						ALLSOURCE DATA CORPORATION PRIVACY POLICY AND SOFTWARE AS A SERVICE
						AGREEMENT
					</h1>
					<p>
						<strong>Effective Date:</strong> July 1, 2025
					</p>
					<p>
						This Privacy Policy and Software as a Service Agreement
						(collectively, the “Agreement&quot;) is entered into by and between
						Allsource Data Corporation, a Delaware corporation with its
						principal place of business at 2701 W Busch Blvd #371, Tampa, FL
						33618 (“Allsource,&quot; “we,&quot; “us,&quot; or “our&quot;), and
						the individual or entity registering for or using the Allsource
						customer intelligence data platform (the “Platform&quot;)
						(“Customer,&quot; “you,&quot; or “your&quot;). By registering an
						account, accessing, or using the Platform, you irrevocably agree to
						be bound by all terms and conditions herein. This Agreement governs
						your use of the Platform and the collection, processing, and
						protection of data submitted to or generated by the Platform.
						Failure to comply with any provision herein constitutes a material
						breach.
					</p>

					<ol>
						<li>
							<h2>DEFINITIONS</h2>
							<h4>1.1 Agreement:</h4>
							<p>
								This Software as a Service Agreement, including any Order Form
								and Statement of Work, and Exhibit A.
							</p>
							<h4>1.2 Allsource Materials:</h4>
							<p>
								The Platform, Documentation, any third-party data made available
								by Allsource, and any Allsource software or technology utilized,
								created, or reduced to practice in the provision of the
								Services.
							</p>
							<h4>1.3 Applicable Data Protection Law:</h4>
							<p>
								All data protection laws, rules, and regulations, each as
								amended from time to time, applicable to a party’s processing of
								Personal Data, including but not limited to the General Data
								Protection Regulation (GDPR), California Consumer Privacy Act
								(CCPA), and other state or international privacy laws.
							</p>
							<h4>1.4 Confidential Information:</h4>
							<p>
								Any data, information, or materials (whether in oral, written,
								electronic, or any other form) of a party (the “Disclosing
								Party&quot;) provided to or learned by the other party (the
								“Receiving Party&quot;) in connection with this Agreement,
								including Allsource Materials, Customer Data, and information
								marked as “confidential&quot; or “proprietary&quot; or
								reasonably understood as such.
							</p>
							<h4>1.5 Customer Data:</h4>
							<p>
								Any query, text, data, and other information provided by
								Customer to Allsource (whether through automated methods via the
								Customer Systems or input directly into the Platform by Users)
								for use with and display through the Platform, including but not
								limited to Customer Transactions (e.g., first name, last name,
								email, transaction amount, timestamp) and Failed Leads (e.g.,
								first name, last name, phone, email, failed lead date).
							</p>
							<h4>1.6 Customer Data:</h4>
							<p>
								Websites, networks, systems, software, and databases made
								available by Customer to Allsource for integration with the
								Platform.
							</p>
							<h4>1.7 Customer Systems:</h4>
							<p>
								Any user manuals and any other instructional, technical, or
								training materials that Allsource provides to Customer in
								printed form or via an Allsource website in connection with the
								Platform, as may be updated by Allsource from time to time.
							</p>
							<h4>1.8 Effective Date:</h4>
							<p>
								{" "}
								The date the Services commence as provided by the Order Form or,
								absent an Order Form, the date of your first access to the
								Platform.
							</p>
							<h4>1.9 Force Majeure Event:</h4>
							<p>
								{" "}
								Events or causes beyond a party’s reasonable control, including
								electrical, internet, or telecommunication outages not caused by
								the obligated party, labor disputes, strikes, lockouts, acts of
								war or terror, riots, acts of God, and governmental actions.
							</p>
							<h4>1.10 Identity Graph:</h4>
							<p>
								{" "}
								Allsource’s database of information about Clients, including
								contact information, internet activity, income levels, family
								information, and other data as described in Section 3.
							</p>
							<h4>1.11 Intellectual Property Rights: </h4>
							<p>
								{" "}
								Patents, copyrights, moral rights, trademarks, trade names,
								service marks, trade dress, trade secrets, and any other form of
								intellectual property rights now or hereafter recognized in any
								jurisdiction, including applications and registrations for any
								of the foregoing.
							</p>
							<h4>1.12 Implementation Services:</h4>
							<p>
								{" "}
								Services to assist Customer in integrating the Platform with
								Customer Systems, as described in Section 2.2.
							</p>
							<h4>1.13 Network: </h4>
							<p>
								{" "}
								The data centers, cloud systems, and network which host the
								Platform.
							</p>
							<h4>1.14 Order Form: </h4>
							<p>
								{" "}
								A document referencing this Agreement that describes the scope
								of the Services to be provided to Customer.
							</p>
							<h4>1.15 Personal Data:</h4>
							<p>
								{" "}
								“Personal data,&quot; “personal information,&quot; and similar
								terms as defined by Applicable Data Protection Law.
							</p>
							<h4>1.16 Professional Support Services:</h4>
							<p> Additional services as provided in Section 2.3.</p>
							<h4>1.17 Services:</h4>
							<p>
								{" "}
								Collectively, (a) Customer’s access to and use of the Platform;
								and (b) Allsource’s provision of all related Implementation
								Services, Support Services, and/or Professional Support
								Services.
							</p>
							<h4>1.18 Subscription Fees:</h4>
							<p>
								{" "}
								Fees payable for Customer’s access to and use of the Platform as
								set forth on an Order Form.
							</p>
							<h4>1.19 Statement of Work:</h4>
							<p>
								{" "}
								Additional services beyond Professional Support Services
								described in the Order Form.
							</p>
							<h4>1.20 Term, Initial Term, and Renewal Term: </h4>
							<p> As defined in Section 10.1.</p>
							<h4>1.21 User: </h4>
							<p>
								{" "}
								An individual authorized by Customer with log-in rights to
								access and use the Platform in accordance with this Agreement.
							</p>
						</li>

						<li>
							<h2>SCOPE OF SERVICES</h2>
							<h4>2.1 Allsource Platform:</h4>
							<p>
								{" "}
								Subject to the terms and conditions of this Agreement, Allsource
								grants to Customer a limited, non-exclusive, revocable right to
								permit and enable Customer (including Users) to access and use
								the Platform during the Term solely in accordance with the terms
								and conditions of this Agreement and to use the Documentation in
								connection with Customer’s exercise of such right.
							</p>
							<h4>2.2 Implementation Services:</h4>
							<p>
								{" "}
								Allsource will provide services to assist Customer in the
								implementation of the Platform, including the integration of the
								Platform with the Customer Systems (the “Implementation
								Services&quot;). The Implementation Services will be described
								in a Statement of Work agreed to in writing by both parties.
								Customer will provide Allsource with any needed unstructured
								(e.g., health policies) and structured data, application
								interfaces, documentation, and all other assistance and support
								necessary to enable Allsource to successfully perform the
								Implementation Services, including providing Allsource with
								access to any applicable Customer Systems required to enable
								integration with the Platform.
							</p>
							<h4>2.3 Professional Support Services: </h4>
							<p>
								{" "}
								Allsource will provide additional services (the “Professional
								Support Services&quot;) as described and pursuant to the hourly
								fee set forth in the Order Form. Any additional services beyond
								the Professional Support Services shall be calculated based on
								Allsource’s customary fees and as provided in a Statement of
								Work.
							</p>
						</li>

						<li>
							<h2>ALLSOURCE RESPONSIBILITIES</h2>
							<h4>3.1 Allsource Personnel; Network:</h4>
							<p>
								Allsource is responsible for the performance of its employees
								and contractors and their compliance with Allsource’s
								obligations under this Agreement. Allsource may use non-employee
								contractors or agents for the purpose of providing Services
								hereunder. Customer acknowledges that the Platform (including
								Customer Data) is hosted and processed on a Network operated by
								a third-party services provider. The Platform (including
								Customer Data) will be hosted and operated in the United States
								of America.
							</p>
							<h4>3.2 Security:</h4>
							<p>
								Allsource has established, and will maintain during the Term,
								commercially reasonable administrative, physical, and technical
								safeguards designed to protect Customer Data commensurate with
								industry standards for the respective Services provided
								hereunder.
							</p>
						</li>

						<li>
							<h2>CUSTOMER RESPONSIBILITIES</h2>
							<h4>4.1 Cooperation: </h4>
							<p>
								{" "}
								Customer’s cooperation is required in order for Allsource to
								efficiently and effectively perform the Services. Customer
								agrees to comply with all of Allsource’s reasonable requests
								made in connection with the provision of Services to Customer.
								Allsource will have no liability for any delays, deficiencies,
								or failures that occur in the performance of Services as a
								result of (a) delays due to unanticipated Customer requests,
								complications with Customer Systems or the Customer Data, (b)
								Customer’s failure to respond in a timely manner to Allsource
								requests (including the cooperation of third parties under
								Customer’s control), or (c) Customer’s material breach of this
								Agreement.
							</p>
							<h4>
								4.2 Responsibility for Customer Data: Customer is responsible
								for:{" "}
							</h4>
							<p>
								{" "}
								(a) ensuring that Customer’s provision or disclosure of the
								Customer Data as contemplated under the Agreement complies with
								all applicable laws (including Applicable Data Protection Law),
								rules, regulations, contracts, policies, and permissions, (b)
								any errors, omissions, or inaccuracies with respect to the
								Customer Data, and (c) maintaining appropriate security,
								protection, and backup of the Customer Data that resides on the
								Customer System. Customer authorizes Allsource to access, store,
								and display the Customer Data contained in any Customer System
								that is integrated with the Platform in connection with
								Allsource’s provision of the Services under this Agreement.
							</p>
							<h4>4.3 Third Party Products and Services: </h4>
							<p>
								{" "}
								Customer is responsible for obtaining and maintaining, at its
								sole cost and expense, any hardware, equipment, third-party
								software, and all Internet browsers and connections required to
								access or use the Platform. Any such hardware, equipment, or
								other third-party products and services required to operate and
								support the Platform will be specified in the Documentation.
							</p>
							<h4>4.4 Responsibility for Other Parties: </h4>
							<p>
								{" "}
								Customer will be liable for any action that it permits, assists,
								or facilitates any of its affiliates, officers, directors,
								employees, contractors, representatives, agents, Users, or other
								entity or organization (other than Allsource, its contractors,
								personnel, or other person or entity acting on its behalf)
								(each, a “Customer Party&quot;) to take related to this
								Agreement, the Customer Data, or the use of the Platform.
								Customer will ensure that all Customer Parties comply with
								Customer’s obligations under this Agreement and that the
								Customer Parties only use the Platform in compliance with all
								applicable laws, rules, and regulations (including consumer and
								data privacy laws).
							</p>
							<h4>4.5 Passwords: </h4>
							<p>
								{" "}
								Customer is responsible for protecting and safeguarding any
								passwords, user IDs, or other credentials and login information
								(collectively, “Passwords&quot;) that have been provided to
								Customer or that are generated in connection with Customer’s use
								of the Platform. Customer will not disclose or make available
								Passwords other than to Users and will use best efforts to
								prevent unauthorized access to, or use of, the Passwords or the
								Platform. Customer is fully responsible for all activities that
								occur in connection with the Passwords. Customer will
								immediately notify Allsource in writing of any unauthorized use
								of the Platform that comes to Customer’s attention.
							</p>
							<h4>4.6 Restrictions: </h4>
							<p>
								{" "}
								Customer will not, and will ensure that its Users will not: (a)
								alter, or permit the alteration of, the Allsource Materials or
								any component thereof, (b) copy, or permit the copying of, the
								Allsource Materials or any component thereof, (c) take any
								action that would foreseeably jeopardize Allsource’s or its
								licensors’ proprietary rights in the Allsource Materials, (d)
								seek to acquire any ownership interest in or to the Allsource
								Materials or any component thereof, (e) attempt to derive source
								or object code from the Allsource Materials or any component
								thereof, (f) publicly perform or demonstrate any Allsource
								Materials or Services, (g) use any Allsource Materials or
								Services for any purpose (including, without limitation, the
								development of any product or service as a replacement of, in
								competition with, or otherwise for use in lieu of the Platform
								or any Services) other than the purpose for which they are
								provided by Allsource, or (h) license, sell, transfer, lease, or
								disclose the Allsource Materials.
							</p>
							<h4>4.7 Acceptable Use: </h4>
							<p>
								{" "}
								Customer may not use the Platform, and will ensure that the
								Users do not use the Platform to: (a) infringe on, violate,
								dilute, or misappropriate the Intellectual Property Rights of
								any third party or any rights of publicity or privacy; (b) store
								or post defamatory, inflammatory, trade libelous, threatening,
								or harassing data; (c) store or post obscene, pornographic, or
								indecent content or data; (d) introduce or propagate any
								unauthorized data, malware, viruses, worms, Trojan horses,
								spyware, worms, other malicious or harmful code; (e) interfere
								with or attempt to interfere with or disrupt the integrity,
								security, functionality, or proper working of the Platform; or
								(f) attempt to discover, access, read, alter, destroy, or damage
								any programs, data, or other information stored on or in
								connection with the Platform by any other party. Customer may
								access the Platform only through interfaces and protocols
								provided or authorized by Allsource.
							</p>
						</li>

						<li>
							<h2>OWNERSHIP RIGHTS</h2>
							<h4>5.1 Allsource Materials: </h4>
							<p>
								{" "}
								As between the Parties, Allsource owns and retains all right,
								title, and interest in and to the Platform, the Documentation,
								any third-party data made available by Allsource, and any
								Allsource software or technology utilized, created, or reduced
								to practice in the provision of the Services (the “Allsource
								Materials&quot;) and all related Intellectual Property Rights.
								Customer acknowledges that (a) no right or interest in the
								Allsource Materials is conveyed other than the limited licenses
								granted herein, (b) the Allsource Materials are protected by
								copyright and other intellectual property laws, and (c) the
								Allsource Materials embody valuable confidential and secret
								information of Allsource or its licensors, the development of
								which required the expenditure of considerable time and money.
								Customer will not take or encourage any action during or after
								the Term that will in any way impair the rights of Allsource in
								and to the Allsource Materials, any proprietary software or
								technology of Allsource, or any Intellectual Property Rights in
								and to any of the foregoing. Customer may not remove or obscure
								any copyright, trademark, and/or proprietary rights notices from
								the Services.
							</p>
							<h4>5.2 Use of Customer Data: </h4>
							<p>
								{" "}
								Customer owns and retains all right, title, and interest in and
								to the Customer Data and all related Intellectual Property
								Rights. Customer consents to Allsource’s use of and access to
								the Customer Data as needed to provide the Services to Customer
								and otherwise in accordance with the terms and conditions of
								this Agreement. Notwithstanding anything in this Agreement to
								the contrary, Allsource may use Customer Data on an aggregated,
								de-identified basis to perform analytic sampling and improve
								Allsource’s provision of the Services, subject in all respects
								to Allsource’s compliance with applicable law.
							</p>
							<h4>5.3 Feedback: </h4>
							<p>
								{" "}
								Customer may, but is not obligated to, provide recommendations,
								suggestions, comments, and other feedback regarding the
								Allsource Materials or the Services. In such event, Allsource
								may use, reproduce, disclose, create derivative works based
								upon, distribute, and otherwise exploit such feedback in
								connection with development, enhancement, improvement,
								distribution, and other exploitation of any Allsource Materials,
								Services, or other products or services. Such feedback is
								provided by Customer “AS IS&quot; and without any warranty of
								any kind. For the avoidance of doubt, feedback will not
								constitute Customer Data or Customer Confidential Information.
								Customer will not use, publish, or otherwise make available to
								any third party any feedback for the development of any product
								or service as a replacement of, in competition with, or
								otherwise for use in lieu of the Platform or any Services.
							</p>
						</li>

						<li>
							<h2>PRIVACY</h2>
							<h4>6.1 Identity Graph: </h4>
							<p>
								{" "}
								Allsource maintains a database of information (the “Identity
								Graph&quot;) that includes information about its customers’
								customers, potential customers, and other individuals
								(collectively, “Clients&quot;). The Identity Graph includes
								information about Clients’ contact information, internet
								activity information, income levels, family information, and
								more as described in Allsource’s Privacy Policy available at
								[insert URL] (“Identity Graph Data&quot;). Customer acknowledges
								that Allsource may use Customer Data, including any Personal
								Data contained in the Customer Data (“Customer Personal
								Data&quot;), to supplement the Identity Graph where consistent
								with your settings in the Platform, at which point such Customer
								Data becomes Identity Graph Data. Customer also acknowledges
								that Allsource makes certain of the Identity Graph Data
								available to its customers in connection with offering its
								Services. The Identity Graph Information, however, will not
								identify Customer (or any other Allsource customer) as the
								source of the Identity Graph Data.
							</p>
							<h4>6.2 Roles and Compliance: Each Party: </h4>
							<p>
								{" "}
								(a) will act as a separate and independent controller of any
								Personal Data received from the other Party; (b) will process
								such Personal Data (i) only for the purposes described in
								Exhibit A and (ii) in compliance with, and provide the same
								level of privacy protection required by, Applicable Data
								Protection Law; (c) may take reasonable and appropriate steps to
								(i) ensure that the other Party processes Personal Data in
								compliance with Applicable Data Protection Law and this
								Agreement and (ii) stop and remediate any unauthorized
								processing of Personal Data; and (d) will notify the other Party
								if it can no longer meet its obligations under Applicable Data
								Protection Law and this Section 6.
							</p>
							<h4>6.3 Data Security: </h4>
							<p>
								{" "}
								Each Party will implement and maintain reasonable security
								procedures and practices designed to protect against
								unauthorized or illegal access to or use, disclosure, or
								modification of Personal Data (a “Security Incident&quot;).
							</p>
							<h4>6.4 Transfers: </h4>
							<p>
								{" "}
								To the extent this Agreement involves the transfer of Personal
								Data across international borders to countries not deemed to
								provide adequate data protection under Applicable Data
								Protection Law, the Parties will conduct such transfers pursuant
								to Module One of the standard contractual clauses available at
								[insert URL] and, in addition and where applicable, the UK’s
								International Data Transfer Addendum, available at [insert URL]
								(collectively, the “SCCs&quot;). The Parties will be deemed to
								have executed the SCCs as of the Effective Date. For transfers
								of Customer Personal Data, Customer will be the “data
								exporter&quot; and Allsource will be the “data importer.&quot;
								For transfers of Identity Graph Data, Allsource will be the
								“data exporter&quot; and Customer will be the “data
								importer.&quot; To implement the SCCs, the parties retain Clause
								7, omit the optional language in Clause 11(a); and Clause 17 and
								Clause 18 shall reference (1) Ireland (for Personal Data
								originating in the European Economic Area), (2) the United
								Kingdom (for Personal Data originating in the United Kingdom),
								and (3) Switzerland (for Personal Data originating in
								Switzerland). References to “Member State&quot; in the SCCs will
								be interpreted as needed to permit the SCCs to effectuate lawful
								transfers of Personal Data and will not prejudice the
								fundamental rights or freedoms of individuals.
							</p>
							<h4>6.5 U.S. Data Export Restrictions: </h4>
							<p>
								{" "}
								In this section, “Covered Person,&quot; “Foreign Person,&quot;
								“Prohibited Transaction,&quot; and “Restricted Transaction&quot;
								have the meaning given those terms under Executive Order 14117
								and rules issued thereunder, including 28 C.F.R. Part 202, and
								“Foreign Adversary&quot; means both “foreign adversary
								country&quot; and an entity that is “controlled by a foreign
								adversary&quot; as those terms are defined under 15 U.S.C. §
								9901. Each Party represents and warrants that it: (1) is not and
								will not be a Covered Person, Foreign Person, or Foreign
								Adversary and (2) will not disclose Personal Data to a Covered
								Person or a Foreign Person. Each Party (the “Notifying
								Party&quot;) will notify the other (the “Notified Party&quot;)
								if the Notifying Party becomes a Covered Person, Foreign Person,
								or Foreign Adversary, in which case the Notified Party may
								terminate the Agreement upon notice to the Notifying Party if
								the Notified Party determines that the Notifying Party’s
								processing of Personal Data pursuant to this Agreement involves
								a Prohibited Transaction or a Restricted Transaction, or
								otherwise violates Applicable Data Protection Law.
							</p>
						</li>

						<li>
							<h2>PAYMENT TERMS</h2>
							<h4>7.1 Fees: </h4>
							<p>
								{" "}
								Customer will pay Allsource the Subscription Fees as set forth
								in the applicable Order Form or Statement of Work. All fees are
								due upfront on a monthly, quarterly, or yearly basis, payable
								via credit card or ACH, as specified in the Order Form. No net
								30 payment terms are offered. Failure to pay fees when due
								constitutes a material breach of this Agreement.
							</p>
							<h4>7.2 Increase in Subscription Fee: </h4>
							<p>
								{" "}
								Allsource may, from time to time, increase the Subscription Fees
								with written notice to Customer at least thirty days prior to a
								Renewal Term. Such increase shall go into effect after notice is
								provided, and on the first day of the applicable Renewal Term.
							</p>
							<h4>7.3 Taxes: </h4>
							<p>
								{" "}
								Customer is responsible for the payment of all taxes that may
								now or in the future be associated with this Agreement or
								Customer’s use of any of the Services (other than taxes based on
								Allsource’s net income). If Allsource is required to pay any
								such tax directly, Customer will, upon receipt of Allsource’s
								notice, promptly reimburse Allsource for any such amount.
							</p>
						</li>

						<li>
							<h2>WARRANTIES AND REMEDIES</h2>
							<h4>8.1 Representations: </h4>
							<p>
								{" "}
								Each party represents and warrants that it has validly entered
								into this Agreement and has the legal power to do so. Each party
								represents and warrants that it will comply with applicable law
								(including regulations, judicial decisions, and other government
								actions) with regard to its performance under this Agreement.
							</p>
							<h4>8.2 Limited Warranty: </h4>
							<p>
								{" "}
								Allsource represents and warrants that: (a) it will perform the
								Services in a professional and workmanlike manner, and (b) the
								Platform will perform in material accordance with the
								Documentation.
							</p>
							<h4>8.3 Disclaimer of Warranty: </h4>
							<p>
								{" "}
								EXCEPT AS SET FORTH IN THIS SECTION 8, THE SERVICES ARE PROVIDED
								ON AN “AS IS&quot; BASIS AND ALL WARRANTIES, CONDITIONS,
								REPRESENTATIONS, INDEMNITIES, AND GUARANTEES WITH RESPECT TO THE
								SERVICES, AND ALL COMPONENTS THEREOF, WHETHER EXPRESS OR
								IMPLIED, ARISING BY LAW, CUSTOM, OR PRIOR ORAL OR WRITTEN
								STATEMENTS MADE BY ALLSOURCE, ITS REPRESENTATIVES, THIRD
								PARTIES, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE
								WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
								AND NON-INFRINGEMENT, ARE HEREBY EXCLUDED AND DISCLAIMED TO THE
								FULLEST EXTENT PERMITTED BY APPLICABLE LAW. ALLSOURCE DOES NOT
								WARRANT THAT THE SERVICES PROVIDED VIA THE PLATFORM WILL BE
								UNINTERRUPTED OR ERROR FREE.
							</p>
							<h4>8.4 Exclusive Remedy: </h4>
							<p>
								{" "}
								If Allsource breaches any warranty provided in Section 8.2, as
								Allsource’s sole liability and Customer’s exclusive remedy,
								Allsource will correct or re-perform any defective Service or,
								if not practicable, Allsource will terminate the affected
								Services and provide Customer with, respectively, a pro rata
								refund of any prepaid, but unused fees, paid by Customer for
								such Services.
							</p>
						</li>

						<li>
							<h2>LIMITATION OF LIABILITY</h2>
							<h4>9.1 Consequential Damages; Liability Limits: </h4>
							<p>
								{" "}
								NEITHER PARTY WILL BE LIABLE TO THE OTHER PARTY UNDER THIS
								AGREEMENT FOR ANY CONSEQUENTIAL, INDIRECT, SPECIAL, EXEMPLARY,
								PUNITIVE, OR INCIDENTAL DAMAGES, WHETHER FORESEEABLE OR
								UNFORESEEABLE, BASED ON OR ARISING UNDER THIS AGREEMENT
								(INCLUDING, BUT NOT LIMITED TO, CLAIMS FOR LOST PROFITS, LOSS OF
								DATA, OR LOSS OF GOODWILL), REGARDLESS OF THE FORM IN WHICH THE
								ACTION IS BROUGHT. FURTHER, THE AGGREGATE LIABILITY THAT
								ALLSOURCE CAN INCUR FOR ALL CLAIMS ARISING UNDER THIS AGREEMENT
								WILL NOT EXCEED THE TOTAL AMOUNT OF FEES PAID BY CUSTOMER TO
								ALLSOURCE DURING THE 12 MONTHS PRIOR TO SUCH CLAIM. THIS SECTION
								WILL BE GIVEN FULL EFFECT EVEN IF ANY REMEDY SPECIFIED IN THIS
								AGREEMENT IS DEEMED TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.
								HOWEVER, THE LIMITATIONS OF LIABILITY SET FORTH IN THIS SECTION
								WILL NOT APPLY TO ANY LIABILITY FOR GROSS NEGLIGENCE,
								INTENTIONAL MISCONDUCT, OR ANY INFRINGEMENT OR MISAPPROPRIATION
								OF THE OTHER PARTY’S TECHNOLOGY, DATA, INTELLECTUAL PROPERTY, OR
								INTELLECTUAL PROPERTY RIGHTS OR TO LIMIT A PARTY’S INDEMNITY
								OBLIGATIONS UNDER THIS AGREEMENT.
							</p>
							<h4>9.2 Loss of Customer Data: </h4>
							<p>
								{" "}
								Customer is solely responsible for maintaining any archival or
								back-up of any Customer Data that Customer may require. Although
								Allsource will use commercially reasonable efforts to protect
								against any unauthorized deletion, destruction, damage, or loss
								of Customer Data in Allsource’s possession or control, Allsource
								will not be responsible or liable for the deletion, correction,
								destruction, damage, loss of, or failure to store, any Customer
								Data or any other data, whether or not resulting from Customer’s
								use of the Platform.
							</p>
						</li>

						<li>
							<h2>INDEMNIFICATION</h2>
							<h4>10.1 Allsource Indemnity: </h4>
							<p>
								{" "}
								Allsource will indemnify, defend, and hold harmless Customer,
								including its officers, directors, employees, and agents,
								against any losses, liabilities, costs, and expenses (including,
								but not limited to, reasonable attorneys’ fees and court costs)
								incurred by Customer resulting from any third-party claim (1)
								that the Platform misappropriates or otherwise violates any of
								such third party’s U.S. Intellectual Property Rights
								(“Infringement Claim&quot;) or (2) related to Allsource’s breach
								of Section 6. If an Infringement Claim occurs, Allsource will,
								at its sole option and expense, either (a) procure for Customer
								the right to continue using the allegedly infringing component
								of the Platform, or (b) replace or modify such allegedly
								infringing component so that it becomes non-infringing, so long
								as functionality of the Platform will not be materially
								adversely affected. If neither alternative is reasonably
								available, Allsource may terminate the Agreement and Allsource
								will provide Customer with a pro rata refund based upon the
								unused portion of any prepaid Subscription Fees for such
								allegedly infringing component on an equitable basis.
								Notwithstanding the foregoing, Allsource will not indemnify
								Customer or be liable for any Infringement Claim based on: (i)
								Customer’s failure to use any updates, modifications,
								corrections, or restorations to the Platform made available by
								Allsource, (ii) Customer’s breach of this Agreement, (iii)
								Customer’s use of the Platform in combination with any software
								not owned, supported, developed, or approved by Allsource, (iv)
								any direction, specification, information, or material provided
								by Customer or a Customer Party, including but not limited to
								the Customer Data, or (v) Customer’s settlement of an
								Infringement Claim without the prior written consent of
								Allsource. The indemnity provided in this Section 10.1 and the
								foregoing remedies constitute Allsource’s sole liability and
								Customer’s exclusive remedy if of an Infringement Claim.
							</p>
							<h4>10.2 Customer Indemnity: </h4>
							<p>
								{" "}
								Customer will indemnify, defend, and hold harmless Allsource,
								including its officers, directors, employees, and agents,
								against any losses, liabilities, costs, and expenses (including
								but not limited to reasonable attorneys’ fees and court costs)
								incurred by Allsource resulting from any third-party claims
								related to (1) Customer’s breach of Section 6 or (2) any
								Customer Data, including any claim that any Customer Data
								infringes, misappropriates, or otherwise violates any of such
								third party’s Intellectual Property Rights or other proprietary
								rights.
							</p>
						</li>

						<li>
							<h2>CONFIDENTIALITY</h2>
							<h4>11.1 Definitions: </h4>
							<p>
								{" "}
								“Confidential Information&quot; means any data, information, or
								materials (whether in oral, written, electronic, or any other
								form) of a party (the “Disclosing Party&quot;) which is provided
								to or learned by the other party (the “Receiving Party&quot;) in
								connection with this Agreement. Confidential Information
								includes data, information, and materials relating to a party’s
								business, finances, products, services, patients, customers,
								personnel, business processes, infrastructure, software and
								hardware, networks, systems, information that is marked as
								“confidential&quot; or “proprietary&quot; at the time of
								disclosure, information that, due to its nature or under the
								circumstances of its disclosure, the Receiving Party knew or had
								reason to know should be treated as confidential or proprietary,
								and any materials which the Disclosing Party obtained from a
								third party subject to an obligation of confidentiality. For the
								avoidance of doubt, the Allsource Materials are the Confidential
								Information of Allsource and Customer Data is the Confidential
								Information of Customer.
							</p>
							<h4>11.2 Exclusions: </h4>
							<p>
								{" "}
								Confidential Information does not include information or data
								that: (a) is or becomes generally known to the public through no
								fault or breach of this Agreement by the receiving party or any
								of its Representatives (as defined below); (b) is rightfully
								known by the receiving party or its Representatives at the time
								of disclosure without an obligation of confidentiality, as
								evidenced by the receiving party’s contemporaneous written
								records; (c) is independently developed or acquired by the
								receiving party or its Representatives without use of the
								disclosing party’s Confidential Information; (d) is rightfully
								received by the receiving party or its Representatives from a
								third party without restriction on use or disclosure; or (e) is
								disclosed with the prior written approval of the disclosing
								party.
							</p>
							<h4>11.3 Confidentiality Obligations: </h4>
							<p>
								{" "}
								The Receiving Party will at all times hold the Confidential
								Information of the Disclosing Party in strict confidence.
								Without limiting the generality of the foregoing, the Receiving
								Party will take reasonable measures, consistent with the
								measures it uses to maintain the confidentiality of its own
								information of similar importance (and in no event using less
								than a reasonable standard of care) to protect against
								unauthorized disclosure or use of the Confidential Information
								of the Disclosing Party. The Receiving Party will limit
								disclosure of Confidential Information of the Disclosing Party
								only to those of its personnel, agents, and authorized
								representatives who (a) need to know such Confidential
								Information for the purpose of this Agreement, (b) have been
								advised of the Receiving Party’s obligations under this
								Agreement, and (c) are under nondisclosure obligations at least
								as protective of the Confidential Information as those set forth
								herein. The Receiving Party will be responsible for any breach
								of this Agreement committed by its personnel, agents, or
								authorized representatives as if such breach were committed by
								the Receiving Party. The Receiving Party will copy and use the
								Confidential Information of the Disclosing Party solely to the
								extent reasonably necessary to exercise its rights and/or
								fulfill its obligations under this Agreement.
							</p>
							<h4>11.4 Compelled Disclosure: </h4>
							<p>
								{" "}
								Notwithstanding anything in this Agreement to the contrary, the
								Receiving Party may disclose Confidential Information of the
								Disclosing Party pursuant to applicable law, regulation,
								subpoena, or order of a court or administrative or regulatory
								entity, provided, however, that, if legally permitted, the
								Receiving Party will promptly give notice of such compelled
								disclosure to the Disclosing Party to allow the Disclosing Party
								to make a reasonable effort to obtain a protective order or
								other confidential treatment of such Confidential Information.
							</p>
							<h4>11.5 Equitable Relief: </h4>
							<p>
								{" "}
								If there is a breach or threatened breach of this Section 11 by
								the Receiving Party, the Disclosing Party may suffer irreparable
								harm and have no adequate remedy at law, and accordingly the
								Disclosing Party will be entitled to seek injunctive and other
								equitable remedies against such breach in addition to allEstados
								Unidos other remedies the Disclosing Party may have at law or
								equity.
							</p>
						</li>

						<li>
							<h2>TERM, TERMINATION, AND SUSPENSION</h2>
							<h4>12.1 Term: </h4>
							<p>
								{" "}
								The term of this Agreement will commence on the Effective Date
								and continue in effect as set forth on the Order Form (the
								“Initial Term&quot/). Except as otherwise specified in the Order
								Form, the Agreement will automatically renew for additional
								one-year periods (each a “Renewal Term,&quot; and collectively
								with the Initial Term, the “Term&quot;), unless either party
								gives the other notice of non-renewal at least thirty (30) days
								before the end of the relevant Initial Term or Renewal Term.
							</p>
							<h4>12.2 Termination for Breach: </h4>
							<p>
								{" "}
								Either Party may terminate this Agreement, upon notice to the
								other Party if the other Party materially breaches this
								Agreement, and such breach remains uncured for 30 days after
								receipt of such written notice specifying the breach.
							</p>
							<h4>12.3 Suspension, Limitation, or Termination: </h4>
							<p>
								{" "}
								Allsource may suspend, terminate, or limit access to the
								Platform at any time if (a) Allsource determines that the
								Platform is being used by Customer in violation of any
								applicable law, rule, or regulation, (b) Allsource determines
								that the Platform is being used by Customer in an unauthorized
								or fraudulent manner or that Customer has submitted fraudulent
								or inaccurate information to Allsource, (c) Allsource determines
								that Customer’s use of the Platform adversely affects
								Allsource’s equipment or service to others, (d) Allsource is
								prohibited by an order of a court or other governmental agency
								from providing the Services, or (e) a security incident or other
								disaster that impacts the Services or the security of Customer
								Data. Allsource will have no liability for any damages,
								liabilities, or losses as a result of any suspension,
								limitation, or termination of Customer’s use of the Services in
								accordance with this Section 12.3.
							</p>
							<h4>12.4 Effect of Termination: </h4>
							<p>
								{" "}
								Upon termination or expiration of this Agreement, all licenses
								and other rights of use granted to Customer under this Agreement
								will immediately cease, and all fees owed and due shall be paid
								to Allsource within five (5) days of the termination date. Each
								party will promptly return to the other Party or destroy all of
								such Party’s Confidential Information then in its possession and
								Allsource will confirm the destruction of the Customer Data. If
								the return or destruction of the other Party’s Confidential
								Information is not feasible, the Confidentiality requirements in
								Section 11 shall survive this Agreement and shall apply to such
								information for the duration the Confidential Information is
								maintained.
							</p>
						</li>

						<li>
							<h2>MISCELLANEOUS</h2>
							<h4>13.1 Entire Agreement; Conflicts: </h4>
							<p>
								{" "}
								This Agreement (including any Order Form or Statement of Work)
								constitutes the entire understanding of the parties with respect
								to the subject matter hereof, and supersedes all prior or
								contemporaneous representations, understandings, proposals, and
								agreements. If a conflict occurs between this Agreement and any
								Statement of Work or Order Form, this Agreement will control
								unless (a) a Statement of Work or Order Form expressly
								identifies a specific provision of this Agreement that is to be
								modified and the manner in which it is to be modified or (b)
								otherwise required by applicable law. The headings of the
								Sections of this Agreement are for reference only and will not
								be deemed to limit, define, or restrict the meaning or substance
								thereof. Any preprinted terms appearing in any Customer purchase
								order or similar document that differ from, are inconsistent
								with, or are in addition to the terms of this Agreement, will be
								void.
							</p>
							<h4>13.2 Assignment: </h4>
							<p>
								{" "}
								Neither party may assign this Agreement, in whole or in part,
								without the other party’s prior written consent, except that
								Allsource may assign this Agreement, in whole or in part, (a) in
								connection with an internal reorganization or a sale of all or
								substantially all of Allsource’s business with which this
								Agreement is associated (whether by acquisition, merger,
								reorganization, consolidation, or similar transaction) without
								the Customer’s prior written consent. Any attempt to assign this
								Agreement other than as permitted above will be null and void.
							</p>
							<h4>13.3 Relationship of the Parties: </h4>
							<p>
								{" "}
								The relationship between the Customer and Allsource is that of
								independent contractors, and this Agreement does not create a
								partnership, franchise, joint venture, agency, fiduciary, or
								employment relationship between the parties or any of their
								affiliates.
							</p>
							<h4>13.4 No Third-Party Beneficiaries: </h4>
							<p>
								{" "}
								This Agreement is intended for the sole and exclusive benefit of
								the parties and is not intended to benefit any third party. Only
								the parties to this Agreement may enforce this Agreement.
							</p>
							<h4>13.5 Publicity: </h4>
							<p>
								{" "}
								The Customer grants Allsource the right to use the Customer’s
								company name and logo for marketing and promotional purposes,
								including on our website and in other public or private
								communications with our existing or potential customers,
								although Customer has the right to decline this usage by sending
								Allsource a notice stating that it does not wish to have their
								use of the Services publicized.
							</p>
							<h4>13.6 Survival: </h4>
							<p>
								{" "}
								All provisions that require continued performance, compliance,
								or effect beyond the termination of this Agreement shall survive
								such termination, including but not limited to Section 6
								(Privacy), Section 7 (Payment Terms), Section 10
								(Indemnification), Section 11 (Confidentiality), and Section
								12.4 (Effect of Termination).
							</p>
							<h4>13.7 Notice: </h4>
							<p>
								{" "}
								All notices required under this Agreement will be in writing and
								will be given by personal delivery, overnight courier service,
								electronic mail, or U.S. mail, certified or registered, postage
								prepaid, return receipt requested, to the parties at their
								respective addresses set forth below, or to either party at any
								other address as notice of which is given in accordance with the
								terms of this Section 13.7. All notices will be deemed effective
								upon personal delivery, upon confirmed receipt if delivered by
								electronic mail, or 1 business day following deposit for
								overnight delivery with any national courier service, or 5 days
								following deposit in the U.S. mail, first class delivery,
								postage prepaid. For Allsource: Allsource Data Corporation, 2701
								W Busch Blvd #371, Tampa, FL 33618, support@allsourcedata.com.
								For Customer: At the Customer’s address or email as provided in
								the Order Form.
							</p>
							<h4>13.8 Force Majeure: </h4>
							<p>
								{" "}
								Neither Party will be responsible for any failure or delay in
								its performance under this Agreement (except for the payment of
								money) due to a Force Majeure Event.
							</p>
							<h4>13.9 Severability; Waiver; Amendment; Counterparts: </h4>
							<p>
								{" "}
								If any provision of this Agreement is held to be unenforceable,
								in whole or in part, such holding will not affect the validity
								of the other provisions of this Agreement. No waiver of or
								amendment to any provision of this Agreement, or any rights or
								obligations of either party under this Agreement, will be
								effective except pursuant to a written instrument signed by both
								parties. All amendments or modifications of this Agreement are
								binding upon the parties so long as such amendments or
								modifications are in writing and executed by the parties. This
								Agreement may be executed in two or more counterparts, each of
								which will be an original, but all of which when taken together
								will constitute one and the same agreement.
							</p>
						</li>

						<li>
							<h2>PRIVACY NOTICE</h2>

							<h4>14.1 Scope:</h4>
							<p>
								This Privacy Notice describes how Allsource Data Corporation and
								our affiliated companies process information about you. This
								Privacy Notice applies to information we collect about
								Representatives of customers and potential customers who access
								or use our websites (collectively, the &quot;Website&quot;) or
								otherwise interact with us, such as through our customer support
								channels. It also applies to information we collect about our
								customers&quot; Clients in connection with providing our
								marketing intelligence services (the &quot;Services&quot;). This
								Privacy Notice is effective as of the Effective Date. We may
								change this Privacy Notice from time to time. If we make
								changes, we will notify you by revising the &quot;Effective
								Date&quot; above. Where required by law, we will notify you of
								changes through the Services or by other means and seek your
								consent to or allow you to opt out of the changes. You are
								responsible for reviewing this Privacy Notice regularly to stay
								informed about our information practices and the choices
								available to you.
							</p>

							<h4>14.2 Collection of Information:</h4>

							<h4>14.2.1 Information You Provide to Us:</h4>
							<p>
								We collect information directly from Representatives when you
								submit a form, request customer support, or otherwise
								communicate with us. The categories of information we collect
								include:
							</p>
							<ul>
								<li>
									Identification Information: Name, email address, and business
									website.
								</li>
								<li>
									Communication Information: Information included in your
									communications with us.
								</li>
								<li>
									We may also collect any other information you choose to
									provide, including Customer Data such as Customer Transactions
									and Failed Leads.
								</li>
							</ul>

							<h4>14.2.2 Information We Collect Automatically:</h4>
							<p>
								We automatically collect the following categories of information
								from Representatives:
							</p>
							<ul>
								<li>
									Internet Activity Information: Information about how you
									access our Website, including data about the device and
									network you use, such as your hardware model, operating system
									version, mobile network, IP address, unique device
									identifiers, and browser type. We also collect information
									about your activity on our Website and interaction with our
									communications, such as access times, browsing behavior (such
									as pages viewed and links clicked), the page you visited
									before navigating to our Website, and information about your
									activity on specific pages.
								</li>
								<li>
									Information Collected by Cookies and Similar Tracking
									Technologies: We use tracking technologies, such as cookies
									and pixels, to collect information about your interactions
									with our Website and communications. These technologies help
									us improve our Website and communications, see which areas and
									features of our Website are popular, count visits, and track
									clicks. You may be able to adjust your browser settings to
									remove or reject browser cookies. [You can also adjust certain
									cookie settings by clicking here.] Please note that removing
									or rejecting cookies could affect the availability and
									functionality of our Services.
								</li>
							</ul>

							<h4>14.2.3 Information We Collect About Clients:</h4>
							<p>
								We collect information about Clients from third parties like
								data vendors and our customers. This information includes name,
								business and personal email address, phone number, LinkedIn
								page, age, profession, income bracket, profession, marital
								status, whether Clients have children, and the Internet Activity
								Information described above.
							</p>

							<h4>14.2.4 Derived Information:</h4>
							<p>
								We may derive information or draw inferences about Clients based
								on the information we collect. For example, we may infer how
								likely a Client is to purchase from our customers based on the
								information we have about that Client.
							</p>

							<h4>14.3 Use of Information:</h4>
							<p>
								We use the categories of information we collect for the
								following business and commercial purposes:
							</p>
							<ul>
								<li>
									Service Delivery: To provide and maintain our Services,
									including to identify Clients and otherwise optimize marketing
									campaigns for our customers.
								</li>
								<li>
									Communication: To communicate with Representatives about
									Allsource and our Services, including to respond to your
									questions, inform you of price or Services changes, and send
									you other transactional or relationship messages.
								</li>
								<li>
									Marketing and Advertising: To send direct marketing messages
									(including via email and automated text) and target
									advertisements to Representatives and Clients on third-party
									platforms and websites. You can opt out of direct marketing
									messages we send by following the instructions in those
									communications (such as by clicking &quot;unsubscribe&quot; in
									the emails or replying &quot;STOP,&quot; &quot;END,&quot; or
									&quot;CANCEL&quot; to the texts) or by [insert opt-out
									instructions].
								</li>
								<li>
									Research and Development: To monitor and analyze Website
									trends, usage, and activities, improve our Website and
									Services, develop new products and services, and generate
									de-identified data that we will not re-identify.
								</li>
								<li>
									Protection and Compliance: To detect, investigate, and help
									prevent security incidents and other malicious, deceptive,
									fraudulent, or illegal activity, help protect the rights and
									property of Allsource and others, and comply with our legal
									and financial obligations.
								</li>
								<li>
									Notice/Consent: We may also use information in other
									circumstances after giving you notice and/or getting your
									consent.
								</li>
							</ul>

							<h4>14.4 Targeted Advertising and Analytics:</h4>
							<p>
								We engage others to provide analytics services, serve
								advertisements, and perform related services across the web and
								in mobile applications. These entities may use cookies, web
								beacons, device identifiers, and other technologies to collect
								information about your use of our Website, including your IP
								address, web browser and mobile network information, pages
								viewed, time spent on pages, and links clicked. This information
								is used to deliver advertising targeted to your interests on
								other companies&quot; sites or mobile apps and to analyze and
								track data, determine the popularity of certain content, and
								better understand your activity. Some of the activities
								described in this section may constitute &quot;targeted
								advertising,&quot; &quot;sharing,&quot; or &quot;selling&quot;
								under certain laws. To opt out of these practices, click [insert
								link]. [In addition to ad targeting activities that rely on
								cookies and similar technologies, we work with advertising
								partners to translate other identifiers, such as your email
								address or phone number, into a unique identifier (called a
								hashed value) that our partners can use to show ads that promote
								Allsource&quot;s or our customers&quot; products and services
								across the web and in mobile apps. Depending on where you
								reside, you may opt out of these disclosures by filling out our
								web form [insert link to opt-out of sale webform].] You can also
								learn more about interest-based ads, or opt out of having your
								web browsing information used for behavioral advertising
								purposes by companies that participate in the Digital
								Advertising Alliance, by visiting [insert DAA link].
							</p>

							<h4>14.5 Disclosure of Information:</h4>
							<p>
								We disclose the categories of information described above as
								follows:
							</p>
							<ul>
								<li>
									Vendors: We disclose information to vendors, service
									providers, contractors, and consultants that need this
									information to provide services to us, such as companies that
									assist us with web hosting, fraud prevention, customer
									service, data enrichment, analytics, and marketing and
									advertising.
								</li>
								<li>
									Customers: We license the &quot;Information We Collect About
									Clients&quot; to our customers.
								</li>
								<li>
									Advertising Partners: We disclose information to third parties
									for the purposes described in the &quot;Marketing and
									Advertising&quot; subsection above.
								</li>
								<li>
									Professional Advisors: We disclose information to our lawyers
									and other professional advisors where necessary to obtain
									advice or otherwise protect and manage our business interests.
								</li>
								<li>
									Legal Authorities: We may disclose information to legal
									authorities and others for the purposes described in the
									&quot;Protection and Compliance&quot; subsection above,
									including if we believe that disclosure is in accordance with,
									or required by, any applicable law or legal process, including
									lawful requests by public authorities to meet national
									security or law enforcement requirements and if we believe
									that your actions are inconsistent with our user agreements or
									policies, if we believe that you have violated the law, or if
									we believe it is necessary to protect the rights, property,
									and safety of Allsource, our users, the public, or others.
								</li>
								<li>
									Corporate Transactions: We reserve the right to disclose
									information in connection with, or during negotiations of
									certain corporate transactions, including the merger, sale of
									Allsource assets, financing, or acquisition of all or a
									portion of our business by another company.
								</li>
								<li>
									Affiliates: We reserve the right to disclose information
									between and among Allsource and any current or future parents,
									affiliates, subsidiaries, and other companies under common
									control and ownership.
								</li>
								<li>
									Consent: We may disclose information when we have your consent
									or you direct us to do so.
								</li>
								<li>
									We also disclose de-identified information that cannot
									reasonably be used to identify you.
								</li>
							</ul>

							<h4>14.6 Residents of Certain US States:</h4>
							<p>
								Privacy laws in certain states (&quot;State Privacy Laws&quot;)
								require additional disclosures and grant their residents certain
								rights. This section applies to residents of California,
								Colorado, Connecticut, Delaware, Iowa, Maryland, Minnesota,
								Montana, Nebraska, New Hampshire, New Jersey, Oregon, Tennessee,
								Texas, Utah, or Virginia and serves as our Notice at Collection
								for California.
							</p>

							<h4>14.6.1 Additional Disclosures:</h4>
							<p>
								We collect identifiers, communication information, and internet
								activity information from Representatives and we collect
								identifiers, characteristics of protected classifications,
								commercial information, professional or employment-related
								information, and derived information about Clients. We collect
								this information from the following categories of sources: we
								collect information directly and by automated means from
								Representatives and we collect information about Clients from
								third-party sources like data vendors and our customers. We
								collect and disclose personal information for the following
								business and commercial purposes: Service Delivery, Research and
								Improvement, Communication, Marketing and Advertising,
								Conducting Analytics, and Protection and Compliance. We do not
								collect information deemed &quot;sensitive&quot; under State
								Privacy Laws and we do not use or disclose sensitive personal
								information to infer characteristics about you.
							</p>

							<h4>14.6.2 Your Privacy Rights:</h4>
							<ul>
								<li>
									Access, Correction, and Deletion: Depending on your state of
									residence, and subject to certain limitations, you have the
									right to (1) request to know more about the categories and
									specific pieces of personal information and access your
									personal information, including in a portable format, (2)
									request deletion of your personal information collected from
									or about you, (3) request correction of inaccurate personal
									information, and (4) request information about the third
									parties to whom we disclosed your personal information. Use
									the &quot;Contact Us&quot; information below to exercise these
									rights. We may verify your request by asking you to verify
									your email address and/or provide information related to your
									recent interactions with us. If we deny your request, you may
									appeal by contacting us as described below.
								</li>
								<li>
									Opt Out of Sales, Sharing, and Targeted Advertising: We sell
									identifiers, characteristics of protected classifications,
									commercial information, communication information, internet
									activity information, professional or employment-related
									information, and derived information relating to Clients to
									our customers. In addition, we process personal information to
									serve you advertisements on non-Allsource properties, expand
									the reach and effectiveness of our own marketing campaigns,
									and allow certain third parties to use this information for
									their own marketing purposes. These activities may be
									considered targeted advertising under State Privacy Laws. We
									do not knowingly &quot;sell&quot; or &quot;share&quot; the
									personal information of consumers under 16 years of age.
									Representatives can opt out of sharing, sales, and targeted
									advertising that occurs on the Website by clicking [insert
									link]. Representatives can also opt out by visiting our
									Website with a legally-recognized universal choice signal
									enabled (such as the Global Privacy Control). Please note that
									our processing of the signal may be limited to the specific
									browser or device that you are using so you may need to renew
									your opt-out choice if you use a different browser or device
									to access our Website, or if you clear your cookies. Clients
									can opt out of sharing, sales, and targeted advertising by
									filling out our web form behind the Your Privacy Choices link
									in the footer of our Website.
								</li>
								<li>
									Nondiscrimination: We will not treat you differently for
									exercising your privacy rights.
								</li>
								<li>
									Appeals: If we deny your request, you may appeal our decision
									by contacting us as described below. If you have concerns
									about the result of an appeal, you may contact the attorney
									general in the state where you reside.
								</li>
								<li>
									Authorized Agents: If you are submitting a rights request as
									an authorized agent, you must submit proof of your
									authorization to make the request, such as a valid power of
									attorney or signed permission from the subject of the request.
									Please do not provide any sensitive personal information in
									connection with this request, such as a driver&quot;s license
									or other government-issued ID. In some cases, we may contact
									the subject of the request for verification. If you are an
									authorized agent seeking to make a request, please contact us
									through the &quot;Contact Us&quot; section below.
								</li>
							</ul>

							<h4>14.6.3 Data Retention:</h4>
							<p>
								We store personal information for as long as necessary to carry
								out the purposes for which we originally collected it, satisfy
								our legal requirements, or for other business purposes explained
								in this Privacy Notice.
							</p>

							<h4>14.6.4 Shine the Light:</h4>
							<p>
								A California law known as &quot;Shine the Light&quot; permits
								residents of California to request certain details about how
								their information is disclosed to third parties for marketing
								purposes. If you are a California resident and would like to
								make such a request, please contact us as described below.
							</p>

							<h4>14.7 Contact Us:</h4>
							<p>
								If you have any questions about this Privacy Notice, please
								contact us at support@allsourcedata.com or Allsource Data
								Corporation, 2701 W Busch Blvd #371, Tampa, FL 33618.
							</p>
						</li>
						<h2>EXHIBIT A: DATA PROCESSING DETAILS AND SUPPORT SERVICES</h2>

						<h3>Details of Processing:</h3>
						<ul>
							<li>
								Purpose: To provide Services, including lookalike modeling and
								insights generation.
							</li>
							<li>
								Categories: Identifiers, transaction data, lead data, enrichment
								features.
							</li>
							<li>
								Roles: Each Party will act as a separate and independent
								controller of any Personal Data received from the other Party.
							</li>
						</ul>

						<h3>
							Technical and Organizational Measures to Ensure the Security of
							Personal Data:
						</h3>

						<h4>Program:</h4>
						<p>
							Each Party will implement and maintain a written information
							security program containing administrative, technical, and
							organizational safeguards appropriate to the risks posed that
							comply with this Exhibit A and that: (a) are designed to protect
							against any Security Incident; and (b) meet or exceed prevailing
							industry standards and requirements under Applicable Data
							Protection Law.
						</p>

						<h4>Access Controls:</h4>
						<p>
							Each Party will: (a) abide by the &quot;principle of least
							privilege,&quot; pursuant to which each Party will permit access
							to Personal Data by its personnel solely on a need-to-know basis;
							and (b) promptly terminate its personnel&quot;s access to Personal
							Data when such access is no longer required for performance under
							the Agreement.
						</p>

						<h4>Account Management:</h4>
						<p>
							Each Party will effectively manage the creation, use, and deletion
							of all account credentials used to access each Party&quot;s
							systems, including by implementing: (a) a segregated account with
							unique credentials for each user; and (b) strict management of
							administrative accounts.
						</p>

						<h4>Vulnerability Management:</h4>
						<p>
							Each Party will: (a) use automated vulnerability scanning tools to
							scan its systems; (b) log vulnerability scan reports; (c) use
							patch management and software update tools where appropriate; and
							(d) prioritize and remediate vulnerabilities by severity.
						</p>

						<h4>Security Segmentation:</h4>
						<p>
							Each Party will monitor, detect, and restrict the flow of
							information on a multilayered basis within its systems using tools
							such as firewalls, proxies, and network-based intrusion detection
							systems.
						</p>

						<h4>Data Loss Prevention:</h4>
						<p>
							Each Party will use data loss prevention measures designed to
							identify, monitor, and protect Personal Data in use, in transit,
							and at rest. Such data loss prevention processes and tools will
							include: (a) automated tools to identify attempts of data
							exfiltration; and (b) the secure and managed use of portable
							devices.
						</p>

						<h4>Encryption:</h4>
						<p>
							Each Party will encrypt, using industry standard encryption tools,
							all Personal Data that each Party: (a) transmits or sends
							wirelessly across public networks or within each Party&quot;s
							systems; and (b) stores on laptops, portable devices, or otherwise
							within each Party&quot;s systems. Each Party will safeguard the
							security and confidentiality of all encryption keys associated
							with encrypted Personal Data.
						</p>

						<h4>Physical Safeguards:</h4>
						<p>
							Each Party will maintain physical access controls designed to
							secure its systems.
						</p>

						<h3>Support Services:</h3>

						<h4>Customer Support:</h4>
						<p>
							If a User requires support regarding the Platform, all requests or
							questions must be first submitted by such User to Customer&quot;s
							designated Tier 1 support representative(s) (each, a
							&quot;Customer Representative&quot;). If a Customer Service
							Representative determines that there is an Error in the Platform
							and is unable to resolve such Error after reasonable efforts, the
							Customer Service Representative may contact Allsource regarding
							such Error. &quot;Error&quot; means an issue which causes the
							Platform or any portion thereof to perform in a manner that
							deviates from its specifications and/or design. Allsource will
							provide Support Services via telephone, e-mail, or other service
							tools used by Allsource in order to address Errors pertaining to
							the Platform. Allsource will use commercially reasonable efforts
							to resolve or provide a workaround for an Error as soon as
							practicable under the circumstances. Allsource will escalate
							Errors by notifying and ensuring the involvement of select
							Allsource senior management individuals as may be required.
						</p>

						<h4>Maintenance Windows:</h4>
						<p>
							Allsource may take down or limit access to the Platform to conduct
							routine maintenance during its scheduled maintenance window, which
							is currently 10:00 p.m. Pacific Time on Sunday through 2:00 a.m.
							Pacific Time on Monday (the &quot;Scheduled Maintenance
							Window&quot;). If Allsource schedules maintenance at any other
							time and anticipates the Platform will be down for more than 2
							minutes at such time, Allsource will advise Customer prior to such
							maintenance. Allsource may change its maintenance window at any
							time upon prior written notice to Customer. Such advice and
							notices may be posted on Allsource&quot;s website.
						</p>

						<h4>Updates:</h4>
						<p>
							Allsource will provide Customer, at no additional charge, all
							updates or modifications to the Platform that Allsource typically
							provides its other customers free of charge. Such updates or
							modifications do not include any new releases of Allsource
							products or services.
						</p>

						<h4>Training Services:</h4>
						<p>
							Allsource will provide training services to Customer regarding the
							use of the Platform as set forth in the Implementation Services
							Statement of Work or as otherwise agreed to in writing by the
							parties. Such training services may include (a) &quot;train the
							trainer&quot; services for the Customer Service Representatives to
							enable such individuals to provide the Tier 1 support services
							described in this Exhibit A, and (b) general training services
							intended for Users on the features, functionality, and use of the
							Platform.
						</p>
					</ol>
					<h2>ACKNOWLEDGMENT AND ACCEPTANCE</h2>

					<p>
						By registering an account, Customer acknowledges having read,
						understood, and agreed to be bound by this Agreement in its
						entirety. Customer must scroll to the bottom of this document and
						check the box below to proceed. Failure to accept constitutes a
						waiver of access to the Platform.
					</p>
				</Paper>
			</Box>

			<Box
				sx={{
					display: "flex",
					justifyContent: "flex-end",
					width: "100%",
				}}
			>
				<Box sx={{ position: "relative", display: "flex", gap: 2 }}>
					<Box
						onMouseEnter={() => setHovered(true)}
						onMouseLeave={() => setHovered(false)}
					>
						<CustomButton
							variant="contained"
							onClick={onAccept}
							disabled={!scrolledToEnd}
						>
							Accept and Continue
						</CustomButton>
					</Box>
					{!scrolledToEnd && hovered && (
						<Box
							sx={{
								position: "absolute",
								top: 30,
								left: 70,
								textWrap: "nowrap",
								p: 1,
								bgcolor: "#fff",
								borderRadius: 0.5,
								filter: "drop-shadow(0 1px 4px #0000001F)",
							}}
							className="paragraph"
						>
							Scroll to the end of the document to enable this button
						</Box>
					)}
				</Box>
			</Box>
		</Box>
	);
};

export default PrivacyPolicy;
