import { SxProps, Theme } from '@mui/system';

export const leadsStyles: { [key: string]: SxProps<Theme> } = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '50vh',
    backgroundColor: '#ffffff',
    width: '100%',
    maxWidth: '25rem',
    maxHeight: '100vh',
    margin: '0 auto',
    position: 'relative',
    boxShadow: '0rem 0.2em 0.8em 0px #00000033',
    borderRadius: '0.625rem',
    border: '0.125rem solid transparent',
    marginTop: '7.5em',
    '@media (max-width: 440px)': {
      boxShadow: '0rem 0px 0px 0px #00000033',
      border: 'none',
      marginTop: '3.75em',
    },
  },
  table_array: {
    fontFamily: 'Nunito', fontSize: '14px', borderRight: '1px solid rgba(235, 235, 235, 1)', fontWeight: '400',
    lineHeight: '19.6px',
    textAlign: 'left',
  },
  table_column: {
    fontFamily: 'Nunito', fontSize: '14px', borderRight: '1px solid rgba(235, 235, 235, 1)', fontWeight: '700',
    lineHeight: '19.6px',
    textAlign: 'left',
  }
  ,
  headers: {
    display: 'flex',
    marginTop: '10px',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    color: 'rgba(244, 87, 69, 1)',
    borderBottom: `1px solid rgba(228, 228, 228, 1)`,
  },
  account: {
    padding: '10px',
    width: '1em',
    color: 'rgba(128, 128, 128, 1)',
    border: '1px solid rgba(184, 184, 184, 1)',
    borderRadius: '3.27px'
  },
  logoContainer: {
    paddingLeft: '2.5em',
    paddingRight: '0.5em',
  },
  title: {
    mt: 1,
    fontWeight: 'bold',
    fontSize: '18px',
    whiteSpace: 'nowrap',
    textAlign: 'start',
    padding: '1.5rem 0rem 0',
    fontFamily: 'Nunito',
  },
  formContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '2em',
    padding: '0 14em',
    '@media (max-width: 900px)': {
      gridTemplateColumns: 'repeat(1, 1fr)',
      padding: '0 2em',
    },
  },
  formWrapper: {
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '280px',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    boxShadow: '0rem 0.2em 0.8em 0px #00000033',
    borderRadius: '0.625rem',
    border: '0.125rem solid transparent',
    padding: '2rem',
  },
  form: {
    width: '100%',
    maxWidth: '360px',
    padding: '220px 0px 24px',
    fontFamily: 'Nunito',
  },
  submitButton: {
    mt: 2,
    backgroundColor: '#F45745',
    color: '#FFFFFF',
    '&:hover': {
      borderColor: '#000000',
      backgroundColor: 'lightgreen',
    },
    fontWeight: 'bold',
    margin: '24px 0px 0 0px',
    textTransform: 'none',
    minHeight: '3rem',
    fontSize: '16px',
    fontFamily: 'Nunito',
  },
};