#!/bin/sh
set -e

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)


FRONTEND_FILE_PATTERN='\.(js|ts|jsx|tsx|json|css|scss|html|md)$'
BACKEND_FILE_PATTERN='\.py$'

FRONTEND_STAGED_FILES=$(echo "$STAGED_FILES" | grep -E "^frontend/.*$FRONTEND_FILE_PATTERN" || true)
BACKEND_STAGED_FILES=$(echo "$STAGED_FILES" | grep -E "^backend/.*$BACKEND_FILE_PATTERN" || true)

if [ -n "$FRONTEND_STAGED_FILES" ]; then
    cd frontend

    FRONTEND_PATHS=$(echo "$FRONTEND_STAGED_FILES" | sed 's|^frontend/||')

    echo "$FRONTEND_PATHS" | xargs npx biome format --write

    cd -

    echo "$FRONTEND_STAGED_FILES" | xargs git add
fi

if [ -n "$BACKEND_STAGED_FILES" ]; then
    cd backend

    source venv/bin/activate

    BACKEND_PATHS=$(echo "$BACKEND_STAGED_FILES" | sed 's|^backend/||')

    echo "$BACKEND_PATHS" | xargs python3 -m ruff format

    cd -

    echo "$BACKEND_STAGED_FILES" | xargs git add
fi
