from sqlalchemy import Column, Integer, TEXT, VARCHAR, TIMESTAMP

from .base import Base


class FiveXFiveUser(Base):
    __tablename__ = '5x5_users'

    id = Column(Integer, primary_key=True)
    up_id = Column(VARCHAR, nullable=True)
    cc_id = Column(VARCHAR, nullable=True)
    first_name = Column(VARCHAR, nullable=True)
    programmatic_business_emails = Column(TEXT, nullable=True)
    mobile_phone = Column(TEXT, nullable=True)
    direct_number = Column(TEXT, nullable=True)
    gender = Column(VARCHAR, nullable=True)
    personal_phone = Column(VARCHAR, nullable=True)
    business_email = Column(VARCHAR, nullable=True)
    personal_emails = Column(VARCHAR, nullable=True)
    last_name = Column(VARCHAR, nullable=True)
    personal_city = Column(VARCHAR, nullable=True)
    personal_state = Column(VARCHAR, nullable=True)
    company_name = Column(VARCHAR, nullable=True)
    company_domain = Column(VARCHAR, nullable=True)
    company_phone = Column(VARCHAR, nullable=True)
    company_sic = Column(VARCHAR, nullable=True)
    company_address = Column(VARCHAR, nullable=True)
    company_city = Column(VARCHAR, nullable=True)
    company_state = Column(VARCHAR, nullable=True)
    company_zip = Column(VARCHAR, nullable=True)
    company_linkedin_url = Column(VARCHAR, nullable=True)
    company_revenue = Column(VARCHAR, nullable=True)
    company_employee_count = Column(VARCHAR, nullable=True)
    net_worth = Column(VARCHAR, nullable=True)
    job_title = Column(VARCHAR, nullable=True)
    sha256_lc_hem = Column(VARCHAR, nullable=True)
    md5_lc_hem = Column(VARCHAR, nullable=True)
    sha1_lc_hem = Column(VARCHAR, nullable=True)
    last_updated = Column(TIMESTAMP, nullable=True)
    personal_emails_last_seen = Column(TIMESTAMP, nullable=True)
    company_last_updated = Column(TIMESTAMP, nullable=True)
    job_title_last_updated = Column(TIMESTAMP, nullable=True)
    first_name_id = Column(Integer, nullable=True)
    last_name_id = Column(Integer, nullable=True)
    age_min = Column(Integer, nullable=True)
    age_max = Column(Integer, nullable=True)
