from sqlalchemy import Column, Integer, TEXT, VARCHAR, TIMESTAMP

from .base import Base


class FiveXFiveUser(Base):
    __tablename__ = '5x5_users'

    id = Column(Integer, primary_key=True)
    up_id = Column(VARCHAR, nullable=True)
    cc_id = Column(VARCHAR, nullable=True)
    first_name = Column(VARCHAR, nullable=True)
    programmatic_business_emails = Column(TEXT, nullable=True)
    mobile_phone = Column(TEXT, nullable=True)
    direct_number = Column(TEXT, nullable=True)
    gender = Column(VARCHAR, nullable=True)
    personal_phone = Column(VARCHAR, nullable=True)
    business_email = Column(VARCHAR, nullable=True)
    personal_emails = Column(VARCHAR, nullable=True)
    last_name = Column(VARCHAR, nullable=True)
    personal_city = Column(VARCHAR, nullable=True)
    personal_state = Column(VARCHAR, nullable=True)
    company_name = Column(VARCHAR, nullable=True)
    company_domain = Column(VARCHAR, nullable=True)
    company_phone = Column(VARCHAR, nullable=True)
    company_sic = Column(VARCHAR, nullable=True)
    company_address = Column(VARCHAR, nullable=True)
    company_city = Column(VARCHAR, nullable=True)
    company_state = Column(VARCHAR, nullable=True)
    company_zip = Column(VARCHAR, nullable=True)
    company_linkedin_url = Column(VARCHAR, nullable=True)
    company_revenue = Column(VARCHAR, nullable=True)
    company_employee_count = Column(VARCHAR, nullable=True)
    net_worth = Column(VARCHAR, nullable=True)
    job_title = Column(VARCHAR, nullable=True)
    last_updated = Column(TIMESTAMP, nullable=True)
    personal_emails_last_seen = Column(TIMESTAMP, nullable=True)
    company_last_updated = Column(TIMESTAMP, nullable=True)
    job_title_last_updated = Column(TIMESTAMP, nullable=True)
    first_name_id = Column(Integer, nullable=True)
    last_name_id = Column(Integer, nullable=True)
    age_min = Column(Integer, nullable=True)
    age_max = Column(Integer, nullable=True)
    additional_personal_emails = Column(TEXT, nullable=True)
    linkedin_url = Column(VARCHAR, nullable=True)
    personal_address = Column(VARCHAR, nullable=True)
    personal_address_2 = Column(VARCHAR, nullable=True)
    personal_zip = Column(VARCHAR, nullable=True)
    personal_zip4 = Column(VARCHAR, nullable=True)
    professional_zip = Column(VARCHAR, nullable=True)
    married = Column(VARCHAR, nullable=True)
    children = Column(VARCHAR, nullable=True)
    income_range = Column(VARCHAR, nullable=True)
    homeowner = Column(VARCHAR, nullable=True)
    seniority_level = Column(VARCHAR, nullable=True)
    department = Column(VARCHAR, nullable=True)
    professional_address = Column(VARCHAR, nullable=True)
    professional_address_2 = Column(VARCHAR, nullable=True)
    professional_city = Column(VARCHAR, nullable=True)
    professional_state = Column(VARCHAR, nullable=True)
    professional_zip4 = Column(VARCHAR, nullable=True)
    primary_industry = Column(VARCHAR, nullable=True)
    business_email_validation_status = Column(VARCHAR, nullable=True)
    business_email_last_seen = Column(TIMESTAMP, nullable=True)
    personal_emails_validation_status = Column(VARCHAR, nullable=True)
    work_history = Column(VARCHAR, nullable=True)
    education_history = Column(VARCHAR, nullable=True)
    company_description = Column(VARCHAR, nullable=True)
    related_domains = Column(VARCHAR, nullable=True)
    social_connections = Column(VARCHAR, nullable=True)
    dpv_code = Column(VARCHAR, nullable=True)
