export const CUSTOM_FIELDS = [
	{ type: "Gender", value: "gender" },
	{ type: "Company Name", value: "company_name" },
	{ type: "Company Domain", value: "company_domain" },
	{ type: "Company SIC", value: "company_sic" },
	{ type: "Company LinkedIn URL", value: "company_linkedin_url" },
	{ type: "Company Revenue", value: "company_revenue" },
	{ type: "Company Employee Count", value: "company_employee_count" },
	{ type: "Net Worth", value: "net_worth" },
	{ type: "Last Updated", value: "last_updated" },
	{ type: "Personal Emails Last Seen", value: "personal_emails_last_seen" },
	{ type: "Company Last Updated", value: "company_last_updated" },
	{ type: "Job Title Last Updated", value: "job_title_last_updated" },
	{ type: "Age Min", value: "age_min" },
	{ type: "Age Max", value: "age_max" },
	{ type: "Additional Personal Emails", value: "additional_personal_emails" },
	{ type: "LinkedIn URL", value: "linkedin_url" },
	{ type: "Married", value: "married" },
	{ type: "Children", value: "children" },
	{ type: "Income Range", value: "income_range" },
	{ type: "Homeowner", value: "homeowner" },
	{ type: "Seniority Level", value: "seniority_level" },
	{ type: "Department", value: "department" },
	{ type: "Primary Industry", value: "primary_industry" },
	{ type: "Work History", value: "work_history" },
	{ type: "Education History", value: "education_history" },
	{ type: "Company Description", value: "company_description" },
	{ type: "Related Domains", value: "related_domains" },
	{ type: "Social Connections", value: "social_connections" },
	{ type: "URL Visited", value: "url_visited" },
	{ type: "Time on site", value: "time_on_site" },
	{ type: "Visited Date", value: "visited_date" },
];
