import { USAStateAbbreviation } from "@mirawision/usa-map-react";

export const allStateAbbreviations = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
];

export const stateNameMap: Record<USAStateAbbreviation, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};

export const stateLabelCoords: Record<
  USAStateAbbreviation,
  { x: number; y: number }
> = {
  AL: { x: 479, y: 313 },
  AK: { x: 87, y: 383 },
  AZ: { x: 147, y: 288 },
  AR: { x: 401, y: 297 },
  CA: { x: 52, y: 226 },
  CO: { x: 234, y: 217 },
  CT: { x: 632, y: 145 },
  DE: { x: 613, y: 197 },
  DC: { x: 593, y: 200 },
  FL: { x: 566, y: 391 },
  GA: { x: 540, y: 322 },
  HI: { x: 220, y: 428 },
  ID: { x: 139, y: 122 },
  IL: { x: 435, y: 200 },
  IN: { x: 475, y: 200 },
  IA: { x: 383, y: 174 },
  KS: { x: 322, y: 229 },
  KY: { x: 497, y: 237 },
  LA: { x: 401, y: 345 },
  ME: { x: 654, y: 78 },
  MD: { x: 598, y: 190 },
  MA: { x: 638, y: 130 },
  MI: { x: 486, y: 143 },
  MN: { x: 369, y: 106 },
  MS: { x: 439, y: 319 },
  MO: { x: 401, y: 235 },
  MT: { x: 209, y: 87 },
  NE: { x: 313, y: 183 },
  NV: { x: 96, y: 192 },
  NH: { x: 638, y: 111 },
  NJ: { x: 616, y: 178 },
  NM: { x: 221, y: 288 },
  NY: { x: 600, y: 131 },
  NC: { x: 589, y: 261 },
  ND: { x: 312, y: 87 },
  OH: { x: 516, y: 191 },
  OK: { x: 346, y: 280 },
  OR: { x: 71, y: 104 },
  PA: { x: 588, y: 174 },
  RI: { x: 648, y: 139 },
  SC: { x: 565, y: 296 },
  SD: { x: 312, y: 134 },
  TN: { x: 490, y: 270 },
  TX: { x: 313, y: 348 },
  UT: { x: 157, y: 208 },
  VT: { x: 624, y: 104 },
  VA: { x: 584, y: 226 },
  WA: { x: 87, y: 52 },
  WV: { x: 544, y: 219 },
  WI: { x: 424, y: 130 },
  WY: { x: 218, y: 147 },
};

export const EASTERN_STATES: USAStateAbbreviation[] = [
  "NH",
  "VT",
  "MA",
  "RI",
  "CT",
  "NJ",
  "DE",
  "MD",
  "DC",
];
