import type { PremiumSync } from "./schemas";

export const sampleSyncs: PremiumSync[] = [
	{
		id: "1",
		name: "Audience 1st half of june",
		created_by: "Mikhail Sofin",
		created_at: "Jun 16, 2025",
		last_sync: "Jun 16, 2025",
		sync_platform: "Meta",
		rows: 7523,
		records_synced: 7523,
		progress: 0.8, // approximate visual progress bar
		status: "syncing",
	},
	{
		id: "2",
		name: "Audience end of may",
		created_by: "Mikhail Sofin",
		created_at: "Jun 1, 2025",
		last_sync: "Jun 1, 2025",
		sync_platform: "Google Upload",
		rows: 24608,
		records_synced: 24608,
		progress: 1,
		status: "synced",
	},
	{
		id: "3",
		name: "Audience 1st half of may",
		created_by: "Mikhail Sofin",
		created_at: "May 15, 2025",
		last_sync: "May 15, 2025",
		sync_platform: "Google Ads",
		rows: 32244,
		records_synced: 32244,
		progress: 1,
		status: "synced",
	},
	{
		id: "4",
		name: "Audience end of april",
		created_by: "Mikhail Sofin",
		created_at: "May 3, 2025",
		last_sync: "May 3, 2025",
		sync_platform: "HubSpot",
		rows: 2300882,
		records_synced: 0,
		progress: 0,
		status: "failed",
	},
	{
		id: "5",
		name: "Audience 1st half of april",
		created_by: "Mikhail Sofin",
		created_at: "Apr 18, 2025",
		last_sync: "Apr 18, 2025",
		sync_platform: "Segment",
		rows: 15476,
		records_synced: 15476,
		progress: 1,
		status: "synced",
	},
	{
		id: "6",
		name: "Audience end of march",
		created_by: "Mikhail Sofin",
		created_at: "Apr 2, 2025",
		last_sync: "Apr 2, 2025",
		sync_platform: "Salesforce",
		rows: 44678,
		records_synced: 44678,
		progress: 1,
		status: "disabled",
	},
];
