from models.base import Base
from datetime import datetime
from sqlalchemy import Column, VARCHAR, Boolean, Integer, Float, TIMESTAMP


class MailchimpUser(Base):
    __tablename__ = 'mailchimp_users'
    id = Column(Integer, primary_key=True, autoincrement=True)
    mailchimp_user_id = Column(VARCHAR)
    email = Column(VARCHAR, nullable=False)
    unique_email_id = Column(VARCHAR)
    contact_id = Column(VARCHAR)
    full_name = Column(VARCHAR)
    web_id = Column(Integer)
    email_type = Column(VARCHAR)
    status = Column(VARCHAR)
    unsubscribe_reason = Column(VARCHAR)
    consents_to_one_to_one_messaging = Column(Boolean)
    merge_fields_property1 = Column(VARCHAR)
    merge_fields_property2 = Column(VARCHAR)
    interests_property1 = Column(Boolean)
    interests_property2 = Column(Boolean)
    stats_avg_open_rate = Column(Float)
    stats_avg_click_rate = Column(Float)
    ecommerce_total_revenue = Column(Float)
    ecommerce_number_of_orders = Column(Integer)
    ecommerce_currency_code = Column(VARCHAR)
    ip_signup = Column(VARCHAR)
    timestamp_signup = Column(TIMESTAMP)
    ip_opt = Column(VARCHAR)
    timestamp_opt = Column(TIMESTAMP)
    member_rating = Column(Integer)
    last_changed = Column(TIMESTAMP)
    language = Column(VARCHAR)
    vip = Column(Boolean)
    email_client = Column(VARCHAR)
    location_latitude = Column(Float)
    location_longitude = Column(Float)
    location_gmtoff = Column(Integer)
    location_dstoff = Column(Integer)
    location_country_code = Column(VARCHAR)
    location_timezone = Column(VARCHAR)
    location_region = Column(VARCHAR)
    marketing_permission_id = Column(VARCHAR)
    marketing_permission_text = Column(VARCHAR)
    marketing_permission_enabled = Column(Boolean)