from sqlalchemy import Column, Integer, VARCHAR, Boolean, TIMESTAMP, BIGINT
from models.base import Base
from datetime import datetime


class ShopifyUser(Base):
    __tablename__ = 'integration_shopify_users'
    id = Column(Integer, primary_key=True, autoincrement=True)
    shopify_user_id = Column(Integer, nullable=False)
    email = Column(VARCHAR, nullable=False)
    created_at = Column(TIMESTAMP, nullable=False, default=datetime.now)
    updated_at = Column(TIMESTAMP, nullable=False)
    first_name = Column(VARCHAR)
    last_name = Column(VARCHAR)
    orders_count = Column(Integer, default=0)
    state = Column(VARCHAR)
    total_spent = Column(VARCHAR, default='0.00')
    last_order_id = Column(BIGINT)
    note = Column(VARCHAR)
    verified_email = Column(Boolean, default=False)
    multipass_identifier = Column(VARCHAR)
    tax_exempt = Column(Boolean, default=False)
    tags = Column(VARCHAR)
    last_order_name = Column(VARCHAR)
    currency = Column(VARCHAR, default='GBP')
    phone = Column(VARCHAR)
    accepts_marketing = Column(Boolean, default=False)
    accepts_marketing_updated_at = Column(TIMESTAMP)
    marketing_opt_in_level = Column(VARCHAR)
    email_marketing_consent_state = Column(VARCHAR)
    email_marketing_consent_opt_in_level = Column(VARCHAR)
    sms_marketing_consent_state = Column(VARCHAR)
    admin_graphql_api_id = Column(VARCHAR)
    address_id = Column(Integer)
    address_first_name = Column(VARCHAR)
    address_last_name = Column(VARCHAR)
    address_company = Column(VARCHAR)
    address1 = Column(VARCHAR)
    address2 = Column(VARCHAR)
    address_city = Column(VARCHAR)
    address_province = Column(VARCHAR)
    address_country = Column(VARCHAR)
    address_zip = Column(VARCHAR)
    address_phone = Column(VARCHAR)
    address_name = Column(VARCHAR)
    address_province_code = Column(VARCHAR)
    address_country_code = Column(VARCHAR)
    address_country_name = Column(VARCHAR)
    address_default = Column(Boolean, default=False)
    