export interface UserData {
	id: number;
	full_name: string;
	owner_full_name?: string;
	company_name?: string;
	email: string;
	created_at: string;
	status?: string;
	is_trial?: boolean;
	last_login: string;
	invited_by_email?: string;
	subscription_plan?: string;
	role: string[];
	team_access_level: string[];
	team_owner_id: number | null;
	pixel_installed_count?: number;
	contacts_count?: number;
	sources_count?: number;
	lookalikes_count?: number;
	credits_count?: number;
	type?: string;
	is_email_validation_enabled: boolean;
	is_another_domain_resolved: boolean;
	has_credit_card: boolean;
	cost_leads_overage: number;
	is_partner: boolean;
	is_master: boolean;
	premium_sources: number;
	whitelabel_settings_enabled?: boolean;
}
